#!/usr/bin/env node

console.log("root level post publish", process.argv);
const pkg = process.env["npm_package_name"];
const version = process.env["npm_package_version"];
const tag = process.env["npm_config_tag"];
const args = process.env["npm_config_argv"];
const event = process.env["npm_lifecycle_event"];
console.log("??", event, pkg, version, tag, args);
