#!/usr/bin/env node
const fs = require("fs-extra");
const { resolve } = require("path");
const pkg = process.env["npm_package_name"];
const version = process.env["npm_package_version"];
const tag = process.env["npm_config_tag"];
const args = process.env["npm_config_argv"];
const event = process.env["npm_lifecycle_event"];
console.log("!!!! [handler ] --> ", event, pkg, version, tag, args);

if (event === "prepublish") {
  const pkg = fs.readJsonSync(
    resolve(__dirname, "../packages/foo/package.json")
  );
  console.log("pkg.version:", pkg.version);
}
